spring.datasource.url=jdbc:postgresql://localhost:5432/aurora
spring.datasource.username=postgres
spring.datasource.password=!Postgre1.
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1

server.port=8080

# After each log event is saved, run enabled ACTIVE rules and create alerts (set false to skip).
aurora.detection.enabled=true


aurora.security.permit-all=false
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/aurora
aurora.security.cors-allowed-origins=http://localhost:4200