-- Aurora SIEM initial schema (aligned with JPA entities in aurora-domain).
-- Hibernate naming: camelCase -> snake_case; PostgreSQL dialect defaults.

CREATE TABLE rule_statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255),
    is_deleted BOOLEAN NOT NULL,
    deleted_at TIMESTAMP(6)
);

CREATE TABLE severities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    level INTEGER,
    description VARCHAR(255),
    is_deleted BOOLEAN NOT NULL,
    deleted_at TIMESTAMP(6)
);

CREATE TABLE alert_statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255),
    is_deleted BOOLEAN NOT NULL,
    deleted_at TIMESTAMP(6)
);

CREATE TABLE sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id VARCHAR(255) NOT NULL UNIQUE,
    hostname VARCHAR(255) NOT NULL,
    ip_address VARCHAR(255),
    os_type VARCHAR(255),
    agent_version VARCHAR(255),
    is_active BOOLEAN NOT NULL,
    last_heartbeat TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL,
    deleted_at TIMESTAMP(6)
);

CREATE TABLE rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    "condition" TEXT NOT NULL,
    enabled BOOLEAN,
    alert_message TEXT,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL,
    deleted_at TIMESTAMP(6),
    status_id BIGINT NOT NULL,
    severity_id BIGINT NOT NULL,
    CONSTRAINT fk_rules_status FOREIGN KEY (status_id) REFERENCES rule_statuses (id),
    CONSTRAINT fk_rules_severity FOREIGN KEY (severity_id) REFERENCES severities (id)
);

CREATE TABLE log_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message TEXT NOT NULL,
    raw_data JSONB,
    timestamp TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    source_id BIGINT NOT NULL,
    severity_id BIGINT,
    CONSTRAINT fk_log_events_source FOREIGN KEY (source_id) REFERENCES sources (id),
    CONSTRAINT fk_log_events_severity FOREIGN KEY (severity_id) REFERENCES severities (id)
);

CREATE TABLE alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message TEXT,
    assigned_to VARCHAR(255),
    investigation_notes TEXT,
    resolved_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6),
    is_deleted BOOLEAN NOT NULL,
    deleted_at TIMESTAMP(6),
    rule_id BIGINT NOT NULL,
    log_event_id BIGINT NOT NULL,
    source_id BIGINT NOT NULL,
    severity_id BIGINT NOT NULL,
    status_id BIGINT NOT NULL,
    CONSTRAINT fk_alerts_rule FOREIGN KEY (rule_id) REFERENCES rules (id),
    CONSTRAINT fk_alerts_log_event FOREIGN KEY (log_event_id) REFERENCES log_events (id),
    CONSTRAINT fk_alerts_source FOREIGN KEY (source_id) REFERENCES sources (id),
    CONSTRAINT fk_alerts_severity FOREIGN KEY (severity_id) REFERENCES severities (id),
    CONSTRAINT fk_alerts_status FOREIGN KEY (status_id) REFERENCES alert_statuses (id)
);

CREATE TABLE incidents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    assigned_to VARCHAR(255),
    timeline TEXT,
    resolved_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6),
    severity_id BIGINT NOT NULL,
    status_id BIGINT NOT NULL,
    CONSTRAINT fk_incidents_severity FOREIGN KEY (severity_id) REFERENCES severities (id),
    CONSTRAINT fk_incidents_status FOREIGN KEY (status_id) REFERENCES alert_statuses (id)
);

CREATE TABLE incident_alerts (
    incident_id BIGINT NOT NULL,
    alert_id BIGINT NOT NULL,
    PRIMARY KEY (incident_id, alert_id),
    CONSTRAINT fk_incident_alerts_incident FOREIGN KEY (incident_id) REFERENCES incidents (id),
    CONSTRAINT fk_incident_alerts_alert FOREIGN KEY (alert_id) REFERENCES alerts (id)
);
